### ISSUE TITLE
打印parentid

### ISSUE THREAD

**Issue by yttas** [sofastack-guides/sofa-tracer-guides#3]
我想在日志里面打印出parentid，但是不想在我自己的controller里面加代码。直接在MDCSpanExtension里面用mdc.put添加
MDC.put(MDCKeyConstants.MDC_PARENTSPANID, sofaTracerSpanContext.getParentId());
这样重新打包并添加这个依赖可以吗？

**Comment by glmapper** [comment]
@yttas SpanExtension 自己扩展下这个接口

**Comment by yttas** [comment]
您好，我现在接口以及扩展了之后，打印出来的parentid 和文档里面提到的traceid,span的命名规则不太对应。
文档里提到，父节点是0.子节点应该是0.1 我这边父节点span ID是0 但是子节点spanid  是0.1.1
![image](https://user-images.githubusercontent.com/38255417/94023961-68761d80-fde9-11ea-87b4-ffb305acccb0.png)
